import type { CollectionConfig } from 'payload'
import { sendProviderApprovalEmail } from '@/utilities/email'

export const ProviderProfiles: CollectionConfig = {
  slug: 'provider-profiles',
  admin: {
    defaultColumns: ['title', 'user', 'approvalStatus', 'accountStatus'],
    useAsTitle: 'title',
  },
  versions: {
    drafts: true,
  },
  access: {
    admin: ({ req }) => req.user?.role === 'admin',
    create: ({ req }) => req.user?.role === 'admin',
    delete: ({ req }) => req.user?.role === 'admin',
    read: ({ req }) => {
      if (req.user?.role === 'admin') return true
      if (req.user?.role === 'provider') {
        return { user: { equals: req.user.id } } as any
      }
      return { approvalStatus: { equals: 'approved' } } as any
    },
    update: ({ req }) => {
      if (req.user?.role === 'admin') return true
      if (req.user?.role === 'provider') {
        return { user: { equals: req.user.id } } as any
      }
      return false
    },
  },
  fields: [
    {
      name: 'user',
      type: 'relationship',
      relationTo: 'users',
      required: true,
      unique: true,
    },
    // slug field - generated by beforeChange hook
    {
      type: 'tabs',
      tabs: [
        {
          label: 'Profile',
          fields: [
            { name: 'title', type: 'text', required: true },
            { name: 'coverImage', type: 'upload', relationTo: 'media' },
            {
              name: 'credentials',
              type: 'array',
              fields: [
                { name: 'name', type: 'text', required: true },
                { name: 'institution', type: 'text' },
                { name: 'year', type: 'number' },
              ],
            },
            { name: 'languages', type: 'relationship', relationTo: 'languages', hasMany: true },
            { name: 'specialties', type: 'relationship', relationTo: 'specialties', hasMany: true },
            {
              name: 'approaches',
              type: 'array',
              fields: [
                {
                  name: 'name',
                  type: 'select',
                  options: [
                    'CBT', 'DBT', 'EMDR', 'Psychodynamic', 'Humanistic',
                    'Solution-Focused', 'ACT', 'Narrative', 'Family Systems',
                  ],
                },
              ],
            },
            { name: 'about', type: 'richText' },
            { name: 'philosophy', type: 'richText' },
            {
              name: 'location',
              type: 'group',
              fields: [
                { name: 'address', type: 'text' },
                { name: 'lat', type: 'number' },
                { name: 'lng', type: 'number' },
              ],
            },
            {
              name: 'religion',
              type: 'select',
              options: [
                { label: 'Islam', value: 'islam' },
                { label: 'Christianity', value: 'christianity' },
                { label: 'Buddhism', value: 'buddhism' },
                { label: 'Hinduism', value: 'hinduism' },
                { label: 'Sikhism', value: 'sikhism' },
                { label: 'Taoism', value: 'taoism' },
                { label: 'No preference', value: 'none' },
              ],
            },
            {
              name: 'faq',
              type: 'array',
              fields: [
                { name: 'question', type: 'text', required: true },
                { name: 'answer', type: 'richText', required: true },
              ],
            },
          ],
        },
        {
          label: 'Sessions',
          fields: [
            { name: 'sessionFee', type: 'number', required: true },
            { name: 'currency', type: 'text', defaultValue: 'MYR' },
            { name: 'acceptsInsurance', type: 'checkbox', defaultValue: false },
            { name: 'offersSlidingScale', type: 'checkbox', defaultValue: false },
            {
              name: 'sessionFormats',
              type: 'array',
              fields: [
                {
                  name: 'format',
                  type: 'select',
                  options: [
                    { label: 'Online', value: 'online' },
                    { label: 'In-Person', value: 'in-person' },
                    { label: 'Both', value: 'both' },
                  ],
                  required: true,
                },
                {
                  name: 'location',
                  type: 'text',
                  admin: {
                    condition: (_, siblingData) =>
                      siblingData?.format === 'in-person' || siblingData?.format === 'both',
                  },
                },
              ],
            },
            { name: 'intakeForm', type: 'relationship', relationTo: 'forms' },
            { name: 'intakeFormRequired', type: 'checkbox', defaultValue: false },
          ],
        },
        {
          label: 'Approval',
          fields: [
            {
              name: 'approvalStatus',
              type: 'select',
              defaultValue: 'pending',
              options: [
                { label: 'Pending', value: 'pending' },
                { label: 'Approved', value: 'approved' },
                { label: 'Rejected', value: 'rejected' },
              ],
              required: true,
            },
            { name: 'approvalNotes', type: 'textarea' },
            { name: 'requestedAt', type: 'date' },
            { name: 'approvedAt', type: 'date' },
            { name: 'approvedBy', type: 'relationship', relationTo: 'users' },
          ],
        },
        {
          label: 'SEO',
          fields: [
            {
              name: 'meta',
              type: 'group',
              fields: [
                { name: 'title', type: 'text' },
                { name: 'description', type: 'textarea' },
                { name: 'image', type: 'upload', relationTo: 'media' },
              ],
            },
          ],
        },
      ],
    },
    {
      name: 'accountStatus',
      type: 'select',
      defaultValue: 'active',
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Inactive', value: 'inactive' },
      ],
      required: true,
    },
  ],
  hooks: {
    beforeChange: [
      async ({ data, operation, req }) => {
        if (operation === 'create' && data?.user && !data?.slug) {
          const user = await req.payload.findByID({
            collection: 'users',
            id: data.user,
          })
          if (user?.name) {
            data.slug = user.name
              .toLowerCase()
              .replace(/[^a-z0-9]+/g, '-')
              .replace(/^-|-$/g, '')
          }
        }
      },
    ],
    afterChange: [
      async ({ doc, previousDoc, req }) => {
        const prevStatus = previousDoc?.approvalStatus
        const newStatus = doc?.approvalStatus
        if (!newStatus || prevStatus === newStatus) return
        if (newStatus !== 'approved' && newStatus !== 'rejected') return

        try {
          const user = await req.payload.findByID({
            collection: 'users',
            id: typeof doc.user === 'object' ? doc.user.id : doc.user,
          })
          if (user?.email) {
            await sendProviderApprovalEmail({
              to: user.email,
              providerName: user.name || 'Provider',
              approved: newStatus === 'approved',
              notes: doc.approvalNotes,
            })
          }
        } catch (err) {
          console.error('Failed to send provider approval email:', err)
        }
      },
    ],
  },
  timestamps: true,
}
